### ISSUE TITLE
Update 1.0.6.6

### ISSUE THREAD

**Issue by HenryQuan** [HenryQuan/WoWs-Info-Origin#23]
It has been a while for IOS update. I also want to update UWP version to support RS.
- [x] Data validation (sometimes pr is corrupted)
- [x] Detect pr corruption 
- [x] Tell user that WG server might be offline
- [x] ~~Explain the situation and inform them the termination of IOS support #20~~ Try Facebook ads
- [X] ~~Show what's new~~ Postponed to future update
- [X] ~~Ask for support per 10 app launches~~ Postponed to future update
- [x] Update support page
- [x] Show android bottom bar #19
- [x] Put my website instead of Patreon
- [x] Fix crashing issue on some devices (List item) #25
- [x] Use exception handler to show an alert to either send this exception to developer or simply discard it

I don't mind making apps for free so I will keep making new apps. I just need to find new ways to get my funds.

**Comment by HenryQuan** [comment]
Ready for update

**Comment by HenryQuan** [comment]
IOS Version is also coming soon.
